"""
Ask CostPilot classification-accuracy golden dataset (Phase 15/18).

Unlike scripts/ask_costpilot_eval_cases.py (which runs real questions
end-to-end against a live database and, optionally, the live model), these
cases test ONLY the deterministic classifier (_ask_intent in
api/routes_efficiency.py) — no DB, no API key, runs in milliseconds. That
makes it practical to have 100+ cases and get a real, reproducible
per-category accuracy number (intent / metric / entity / date) instead of
an end-to-end pass/fail that conflates many failure causes into one bit.

Each case's `expected` dict only lists fields worth asserting -- a case
that legitimately doesn't care about date interpretation just omits
`period_key`, and is not counted against date accuracy.
"""

CASES = [
    # ============================================================
    # LEVEL 1 — Basic totals
    # ============================================================
    {"id": "l1_01", "persona": "executive", "difficulty": 1,
     "question": "How much are we spending on AI?",
     "expected": {"intent": "total", "metric": "spend_usd"}},
    {"id": "l1_02", "persona": "cfo", "difficulty": 1,
     "question": "How much did we spend on AI last month?",
     "expected": {"intent": "total", "metric": "spend_usd", "period_key": "last_month"}},
    {"id": "l1_03", "persona": "cfo", "difficulty": 1,
     "question": "How much have we spent year to date?",
     "expected": {"metric": "spend_usd", "period_key": "this_year"}},
    {"id": "l1_04", "persona": "finops", "difficulty": 1,
     "question": "What is our average cost per request?",
     "expected": {"metric": "avg_cost_per_request"}},
    {"id": "l1_05", "persona": "developer", "difficulty": 1,
     "question": "How many tokens have we used?",
     "expected": {"metric": "total_tokens"}},
    {"id": "l1_06", "persona": "cfo", "difficulty": 1,
     "question": "How much has token pruning saved us?",
     "expected": {"metric": "tokens_saved", "intent": "pruning"}},
    {"id": "l1_07", "persona": "executive", "difficulty": 1,
     "question": "What did we spend this quarter?",
     "expected": {"metric": "spend_usd", "period_key": "this_quarter"}},
    {"id": "l1_08", "persona": "manager", "difficulty": 1,
     "question": "How much AI budget is left this month?",
     "expected": {"intent": "budget"}},
    {"id": "l1_09", "persona": "executive", "difficulty": 1,
     "question": "How many AI requests have we made this week?",
     "expected": {"metric": "request_count", "period_key": "this_week"}},
    {"id": "l1_10", "persona": "governance", "difficulty": 1,
     "question": "Show the latest risk events.",
     "expected": {"intent": "risk_events"}},
    {"id": "l1_11", "persona": "developer", "difficulty": 1,
     "question": "How many input tokens did we use?",
     "expected": {"metric": "input_tokens"}},
    {"id": "l1_12", "persona": "developer", "difficulty": 1,
     "question": "How many output tokens did we use last month?",
     "expected": {"metric": "output_tokens", "period_key": "last_month"}},
    {"id": "l1_13", "persona": "executive", "difficulty": 1,
     "question": "What was our AI usage yesterday?",
     "expected": {"period_key": "yesterday"}},
    {"id": "l1_14", "persona": "cfo", "difficulty": 1,
     "question": "How much did we spend today?",
     "expected": {"period_key": "today"}},
    {"id": "l1_15", "persona": "cfo", "difficulty": 1,
     "question": "What is our AI bill this month?",
     "expected": {"metric": "spend_usd", "period_key": "this_month"}},

    # ============================================================
    # LEVEL 2 — Filtering (department / person / account / model / provider)
    # ============================================================
    {"id": "l2_01", "persona": "manager", "difficulty": 2,
     "question": "How much has my department spent this month?",
     "expected": {"entity": "department", "period_key": "this_month"}},
    {"id": "l2_02", "persona": "manager", "difficulty": 2,
     "question": "What did Sales spend last month?",
     # entity classification for a *named* department (not the literal
     # word "department") happens one layer up in _ask_costpilot_answer,
     # via _ask_named_department, which needs real DB data _ask_intent
     # deliberately never touches -- verified correct end-to-end
     # separately (see tests/test_ask_costpilot.py department-scope tests).
     "expected": {"period_key": "last_month"}},
    {"id": "l2_03", "persona": "pm", "difficulty": 2,
     "question": "What was the AI cost for Acme last quarter?",
     "expected": {"period_key": "last_quarter"}},
    {"id": "l2_04", "persona": "developer", "difficulty": 2,
     "question": "How much are we spending on Claude?",
     "expected": {"provider": "Anthropic"}},
    {"id": "l2_05", "persona": "developer", "difficulty": 2,
     "question": "How much are we spending on OpenAI?",
     "expected": {"provider": "OpenAI"}},
    {"id": "l2_06", "persona": "finops", "difficulty": 2,
     "question": "How much did we spend using GPT models?",
     "expected": {"provider": "OpenAI"}},
    {"id": "l2_07", "persona": "governance", "difficulty": 2,
     "question": "Which platform sends us the most traffic?",
     "expected": {"entity": "platform"}},
    {"id": "l2_08", "persona": "finops", "difficulty": 2,
     "question": "Which provider handled the most requests?",
     "expected": {"entity": "provider", "metric": "request_count"}},
    {"id": "l2_09", "persona": "pm", "difficulty": 2,
     "question": "Which users worked on this account?",
     "expected": {"entity": "person"}},
    {"id": "l2_10", "persona": "developer", "difficulty": 2,
     "question": "Which agent generated the most requests?",
     "expected": {"entity": "agent", "metric": "request_count"}},
    {"id": "l2_11", "persona": "manager", "difficulty": 2,
     "question": "Who on my team is using the most AI?",
     "expected": {"entity": "person"}},
    {"id": "l2_12", "persona": "finops", "difficulty": 2,
     "question": "Which model uses the most tokens per request?",
     "expected": {"entity": "model"}},
    {"id": "l2_13", "persona": "cfo", "difficulty": 2,
     "question": "Which accounts generated the most AI cost?",
     "expected": {"entity": "account", "metric": "spend_usd"}},
    {"id": "l2_14", "persona": "developer", "difficulty": 2,
     "question": "Which agent cost us the most?",
     "expected": {"entity": "agent", "metric": "spend_usd"}},
    {"id": "l2_15", "persona": "pm", "difficulty": 2,
     "question": "Show monthly AI spend for this project.",
     "expected": {"entity": "context"}},

    # ============================================================
    # LEVEL 3 — Aggregation (breakdown / ranking / top-N)
    # ============================================================
    {"id": "l3_01", "persona": "cfo", "difficulty": 3,
     "question": "Show AI spend by department.",
     "expected": {"entity": "department", "metric": "spend_usd"}},
    {"id": "l3_02", "persona": "cfo", "difficulty": 3,
     "question": "Which five users generated the most AI cost?",
     "expected": {"intent": "ranking", "entity": "person", "result_limit": 5}},
    {"id": "l3_03", "persona": "developer", "difficulty": 3,
     "question": "Who used the most tokens yesterday?",
     "expected": {"intent": "ranking", "entity": "person", "period_key": "yesterday"}},
    {"id": "l3_04", "persona": "executive", "difficulty": 3,
     "question": "Which department spent the most this year?",
     "expected": {"intent": "ranking", "entity": "department", "period_key": "this_year"}},
    {"id": "l3_05", "persona": "cfo", "difficulty": 3,
     "question": "Which models cost us the most?",
     "expected": {"intent": "ranking", "entity": "model", "metric": "spend_usd"}},
    {"id": "l3_06", "persona": "developer", "difficulty": 3,
     "question": "Who are the top 10 users by AI spend?",
     "expected": {"intent": "ranking", "entity": "person", "result_limit": 10}},
    {"id": "l3_07", "persona": "developer", "difficulty": 3,
     "question": "Show me the top 3 agents by request volume.",
     "expected": {"intent": "ranking", "entity": "agent", "result_limit": 3}},
    {"id": "l3_08", "persona": "manager", "difficulty": 3,
     "question": "Who had the fewest tokens used last week?",
     "expected": {"intent": "ranking", "direction": "asc", "period_key": "last_week"}},
    {"id": "l3_09", "persona": "finops", "difficulty": 3,
     "question": "Which department has the highest cost per request?",
     "expected": {"entity": "department", "metric": "avg_cost_per_request"}},
    {"id": "l3_10", "persona": "cfo", "difficulty": 3,
     "question": "Which account generated the most AI spend?",
     "expected": {"intent": "ranking", "entity": "account"}},
    {"id": "l3_11", "persona": "governance", "difficulty": 3,
     "question": "Which departments have the most AI activity?",
     "expected": {"entity": "department", "metric": "request_count"}},
    {"id": "l3_12", "persona": "developer", "difficulty": 3,
     "question": "Show request volume by model.",
     "expected": {"entity": "model", "metric": "request_count"}},
    {"id": "l3_13", "persona": "manager", "difficulty": 3,
     "question": "Which accounts are driving our spend?",
     "expected": {"entity": "account"}},
    {"id": "l3_14", "persona": "finops", "difficulty": 3,
     "question": "Who is using the most expensive models?",
     "expected": {"metric": "spend_usd"}},
    {"id": "l3_15", "persona": "cfo", "difficulty": 3,
     "question": "Give me a month-by-month breakdown.",
     "expected": {}},

    # ============================================================
    # LEVEL 4 — Comparison
    # ============================================================
    {"id": "l4_01", "persona": "executive", "difficulty": 4,
     "question": "What was our spend this month compared with last month?",
     "expected": {"intent": "comparison"}},
    {"id": "l4_02", "persona": "cfo", "difficulty": 4,
     "question": "Are we spending more than this time last year?",
     "expected": {"intent": "comparison"}},
    {"id": "l4_03", "persona": "executive", "difficulty": 4,
     "question": "This year vs last year.",
     "expected": {"intent": "comparison"}},
    {"id": "l4_04", "persona": "finops", "difficulty": 4,
     "question": "Compare OpenAI and Anthropic spend.",
     "expected": {"intent": "comparison"}},
    {"id": "l4_05", "persona": "manager", "difficulty": 4,
     "question": "Compare my team with last month.",
     "expected": {"intent": "comparison"}},
    {"id": "l4_06", "persona": "cfo", "difficulty": 4,
     "question": "Did our cost per request improve?",
     "expected": {"metric": "avg_cost_per_request"}},
    {"id": "l4_07", "persona": "finops", "difficulty": 4,
     "question": "Are we using fewer tokens per request?",
     "expected": {}},
    {"id": "l4_08", "persona": "executive", "difficulty": 4,
     "question": "What was my spend last year compared with this year?",
     "expected": {"intent": "comparison"}},
    {"id": "l4_09", "persona": "cfo", "difficulty": 4,
     "question": "Show month-over-month AI spend.",
     "expected": {"period_key": "this_month"}},
    {"id": "l4_10", "persona": "finops", "difficulty": 4,
     "question": "Did switching models save us money?",
     "expected": {}},

    # ============================================================
    # LEVEL 7 — Diagnostic / why (deterministic, not LLM speculation)
    # ============================================================
    {"id": "l7_01", "persona": "executive", "difficulty": 7,
     "question": "Why did our AI spend increase this month?",
     "expected": {"intent": "change_drivers"}},
    {"id": "l7_02", "persona": "manager", "difficulty": 7,
     "question": "What caused our spend to increase?",
     "expected": {"intent": "change_drivers"}},
    {"id": "l7_03", "persona": "finops", "difficulty": 7,
     "question": "What caused the spike yesterday?",
     "expected": {"intent": "change_drivers"}},
    {"id": "l7_04", "persona": "executive", "difficulty": 7,
     "question": "Why did our bill jump?",
     "expected": {"intent": "change_drivers"}},
    {"id": "l7_05", "persona": "cfo", "difficulty": 7,
     "question": "What drove the increase in spend this quarter?",
     "expected": {"intent": "change_drivers"}},
    {"id": "l7_06", "persona": "manager", "difficulty": 7,
     "question": "Who had the largest increase in usage this month?",
     "expected": {"intent": "ranking"}},
    {"id": "l7_07", "persona": "governance", "difficulty": 7,
     "question": "Are there users generating unusual amounts of activity?",
     "expected": {}},  # UNSUPPORTED_CURRENTLY -- see question catalog doc

    # ============================================================
    # LEVEL 8 — Adversarial: typos, bad grammar, messy real-world phrasing
    # ============================================================
    {"id": "l8_01", "persona": "adversarial", "difficulty": 8,
     "question": "what did sales spend",
     # See l2_02 -- named-department entity promotion happens above _ask_intent.
     "expected": {"metric": "spend_usd"}},
    {"id": "l8_02", "persona": "adversarial", "difficulty": 8,
     "question": "how much sheldon use",
     "expected": {}},
    {"id": "l8_03", "persona": "adversarial", "difficulty": 8,
     "question": "who burning the most tokens",
     "expected": {"metric": "total_tokens"}},
    {"id": "l8_04", "persona": "adversarial", "difficulty": 8,
     "question": "what model costing us the most",
     "expected": {"entity": "model", "metric": "spend_usd"}},
    {"id": "l8_05", "persona": "adversarial", "difficulty": 8,
     "question": "did we spend more this month",
     "expected": {"period_key": "this_month"}},
    {"id": "l8_06", "persona": "adversarial", "difficulty": 8,
     "question": "how much money costpilot save us",
     # Matches the "savings_total" canonical pattern -- a distinct, richer
     # analysis (premium-tier spend + projected annual savings) than a
     # plain tokens_saved total, so metric=spend_usd here is correct,
     # deliberate behavior, not a misclassification.
     "expected": {"intent": "savings"}},
    {"id": "l8_07", "persona": "adversarial", "difficulty": 8,
     "question": "who went crazy on tokens yesterday",
     "expected": {"period_key": "yesterday"}},
    {"id": "l8_08", "persona": "adversarial", "difficulty": 8,
     "question": "how are we doing vs budget",
     "expected": {"intent": "budget"}},
    {"id": "l8_09", "persona": "adversarial", "difficulty": 8,
     "question": "are we gonna run out of budget",
     "expected": {"intent": "budget"}},
    {"id": "l8_10", "persona": "adversarial", "difficulty": 8,
     "question": "top ppl by toknes",
     "expected": {"intent": "ranking"}},
    {"id": "l8_11", "persona": "adversarial", "difficulty": 8,
     "question": "show spend for account that doesn't exist",
     "expected": {"metric": "spend_usd"}},
    {"id": "l8_12", "persona": "adversarial", "difficulty": 8,
     "question": "SHOW ME CLAUDE SPEND",
     "expected": {"provider": "Anthropic"}},
    {"id": "l8_13", "persona": "adversarial", "difficulty": 8,
     "question": "what about marketing",
     # See l2_02 -- named-department entity promotion happens above _ask_intent.
     "expected": {}},
    {"id": "l8_14", "persona": "adversarial", "difficulty": 8,
     "question": "show me claude",
     "expected": {"provider": "Anthropic"}},
    {"id": "l8_15", "persona": "adversarial", "difficulty": 8,
     "question": "how much did we save from pruning last month tho",
     "expected": {"metric": "tokens_saved", "period_key": "last_month"}},

    # ============================================================
    # Date torture tests (Phase 7)
    # ============================================================
    {"id": "date_01", "persona": "date", "difficulty": 3,
     "question": "What was our spend today?", "expected": {"period_key": "today"}},
    {"id": "date_02", "persona": "date", "difficulty": 3,
     "question": "What was our spend yesterday?", "expected": {"period_key": "yesterday"}},
    {"id": "date_03", "persona": "date", "difficulty": 3,
     "question": "What was our spend this week?", "expected": {"period_key": "this_week"}},
    {"id": "date_04", "persona": "date", "difficulty": 3,
     "question": "What was our spend last week?", "expected": {"period_key": "last_week"}},
    {"id": "date_05", "persona": "date", "difficulty": 3,
     "question": "What was our spend in the past 7 days?", "expected": {"days": 7}},
    {"id": "date_06", "persona": "date", "difficulty": 3,
     "question": "What was our spend in the past 30 days?", "expected": {"days": 30}},
    {"id": "date_07", "persona": "date", "difficulty": 3,
     "question": "What was our spend this month?", "expected": {"period_key": "this_month"}},
    {"id": "date_08", "persona": "date", "difficulty": 3,
     "question": "What was our spend last month?", "expected": {"period_key": "last_month"}},
    {"id": "date_09", "persona": "date", "difficulty": 3,
     "question": "What was our spend this quarter?", "expected": {"period_key": "this_quarter"}},
    {"id": "date_10", "persona": "date", "difficulty": 3,
     "question": "What was our spend last quarter?", "expected": {"period_key": "last_quarter"}},
    {"id": "date_11", "persona": "date", "difficulty": 3,
     "question": "What is our spend year to date?", "expected": {"period_key": "this_year"}},
    {"id": "date_12", "persona": "date", "difficulty": 3,
     "question": "What was our spend last year?", "expected": {"period_key": "last_year"}},
    {"id": "date_13", "persona": "date", "difficulty": 4,
     "question": "What was our spend around this time last year?",
     "expected": {"period_key": "same_range_last_year"}},
    {"id": "date_14", "persona": "date", "difficulty": 3,
     "question": "What was our spend since inception?", "expected": {"period_key": "all_time"}},
    {"id": "date_15", "persona": "date", "difficulty": 3,
     "question": "What was our spend over the last 12 months?", "expected": {}},
    {"id": "date_16", "persona": "date", "difficulty": 4,
     "question": "Show month over month spend trends.", "expected": {"period_key": "this_month"}},
    {"id": "date_17", "persona": "date", "difficulty": 4,
     "question": "Show quarter over quarter spend.", "expected": {"period_key": "this_quarter"}},
    {"id": "date_18", "persona": "date", "difficulty": 4,
     "question": "Show year over year spend.", "expected": {"period_key": "this_year"}},
    {"id": "date_19", "persona": "date", "difficulty": 2,
     "question": "What was our spend in the last 3 days?", "expected": {"days": 3}},
    {"id": "date_20", "persona": "date", "difficulty": 2,
     "question": "What was our spend in the last 90 days?", "expected": {"days": 90}},

    # ============================================================
    # Messy real-world synonyms (Phase 3)
    # ============================================================
    {"id": "syn_01", "persona": "synonym", "difficulty": 2,
     "question": "What's our AI burn rate?", "expected": {"metric": "total_tokens"}},
    {"id": "syn_02", "persona": "synonym", "difficulty": 2,
     "question": "How much AI consumption did we have?", "expected": {"metric": "total_tokens"}},
    {"id": "syn_03", "persona": "synonym", "difficulty": 2,
     "question": "What's our AI activity this week?", "expected": {"period_key": "this_week"}},
    {"id": "syn_04", "persona": "synonym", "difficulty": 2,
     "question": "What's our cheapest model?", "expected": {"entity": "model"}},
    {"id": "syn_05", "persona": "synonym", "difficulty": 2,
     "question": "Who's the worst offender on token usage?", "expected": {"metric": "total_tokens"}},
    {"id": "syn_06", "persona": "synonym", "difficulty": 2,
     "question": "How much avoided cost did pruning give us?", "expected": {"metric": "tokens_saved"}},
    {"id": "syn_07", "persona": "synonym", "difficulty": 2,
     "question": "What's our run rate this month?", "expected": {"period_key": "this_month"}},
    {"id": "syn_08", "persona": "synonym", "difficulty": 2,
     "question": "How much AI traffic did we get today?", "expected": {"metric": "request_count", "period_key": "today"}},
]
